[[redirects]]
from = "/*"
to="/index.html"
status = 200

/margaret
/swipper
/picture
/dollieblair
/foodanddrink
/asteroids-dollie
/abriefhistory
/selecting-dollie
/telescopes-dollie
/medicalcare-dollie
/moongazing-dollie
/moon-edward
/dude-gussie
/moonred-dollie
/advertising-food
/agood-food
/asteroid-food
/astronomy-food
/baby-food
/radio-food
/advertisingoutdoors-food
/astreoids2-food
/astronomyorastrology-food
/autoresponder-food
/babymonitor-food
/radioastronomy-food
/choosing















































